name: PR Test builds
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
    - name: Verify emsdk
      run: emcc -v