name: Build and Publish WASM
on:
  pull_request: 
    branches: ["main"]
env:
  PLATFORM: PLATFORM_WEB
  MAKE: /usr/bin/make
  PYTHON_PATH: /usr/bin
  GITHUB_SHA: ${{ github.sha }}
  REPO: ${{ github.repository }}  
jobs:
  build:
    name: Build WASM for Merge
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - name: Verify
        run: emcc -v